name: CI-S

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint frontend Helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint ci/helm/frontend/ -f ci/helm/frontend/values-staging.yaml
      - name: Lint backend Helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: helm lint ci/helm/backend/ -f ci/helm/backend/values-staging.yaml

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DO Registry
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com
          username: ${{ secrets.KUBE_TOKEN }}
          password: ${{ secrets.KUBE_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: ci/node-backend
          push: true
          tags: registry.digitalocean.com/omega/node-backend-staging:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v2
        with:
          context: ci/node-frontend
          push: true
          tags: registry.digitalocean.com/omega/node-frontend-staging:latest

      - name: Build and push spider
        uses: docker/build-push-action@v2
        with:
          context: ci/spider
          push: true
          tags: registry.digitalocean.com/omega/spider:latest

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.KUBE_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 winery

      - name: Install Helm
        run: sudo snap install helm --classic

      #- name: Add Mongo repo
      #  run: helm repo add bitnami https://charts.bitnami.com/bitnami

      #- name: Apply Mongo chart
      #  run: helm upgrade --install --wait --atomic mongo bitnami/mongodb -f ci/helm/mongo/values.yaml -n staging

      - name: Apply backend chart
        run: helm upgrade --install --wait --atomic backend ci/helm/backend/ -f ci/helm/backend/values-staging.yaml -n staging

      - name: Apply frontend chart
        run: helm upgrade --install --wait --atomic frontend ci/helm/frontend/ -f ci/helm/frontend/values-staging.yaml -n staging
    needs: lint-helm
